# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170113_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
