# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170113_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=False),
        ),
    ]
