# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20170113_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
